# This is a basic workflow to help you get started with Actions

name: BUILD—TOMCAT-IMAGES

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
#变量配置      
env:
  #镜像名称
  IMAGE_NAME: tomcat
  #镜像tag
  IMAGE_TAG: 9.0.89-jdk8-temurin-focal
  #dockerHub仓库名称
  DOCKER_REGISTRY: chtsen
jobs:
  build-image:
    #运行的环境  
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
      # 拉取代码，同时获取tag，如果获取不到则默认值为edge，并赋值给v变量
      - uses: actions/checkout@v3
      - name: Modify file
        run: |
           sed -i s#IMAGE_TAG#${{ env.IMAGE_TAG }}#g ./tomcat/Dockerfile
           
     # Docker配置多平台环境
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2          
      # 登录镜像仓库
      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
        #这里引用的变量为上一步配置的变量
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PW }}     
      # 打包构建并推送
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./tomcat/Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          #推送到镜像仓库  
          push: true
          # 这里会构建两个版本镜像，
          # 1.dweizhao/backend:latest
          # 2.  output-id步骤中获取的v，构建dweizhao/backend:edge或者dweizhao/backend:对应tag值
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}-uuid
           # ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
